name: Build Package
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.25.0
        
      - name: 构建plugin
        run: |
          pnpm install
          pnpm run build
          mkdir -p ${{ runner.temp }}/temp/plugin
          cp -r README.md LICENSE ${{ runner.temp }}/temp/plugin

      - name: 处理构建产物
        run: |
          pnpm pkg delete devDependencies
          cp -r package.json CHANGELOG.md resources config lib ${{ runner.temp }}/temp/plugin
        working-directory: packages/core

      - name: 上传plugin构建产物
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: ${{ runner.temp }}/temp/plugin
